{
  "hash": "b60dced18011083b354819ce90948ac4",
  "result": {
    "markdown": "---\ntitle: \"Hello, Penguins!\"\nformat: \n  html: default\n  pdf: default\neditor: visual\nexecute:\n  echo: true\nbibliography: references.bib\n---\n\n\n\n# Introduction\n\n## Data {.smaller}\n\nFor this analysis we'll use the `penguins` dataset from the [**palmerpenguins**](https://allisonhorst.github.io/palmerpenguins/) package.[@gorman2014]\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ggthemes)\nlibrary(palmerpenguins)\nlibrary(gt)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 344\nColumns: 8\n$ species           <fct> Adelie, Adelie, Adelie, Adelie, Adelie, Adelie, Adel~\n$ island            <fct> Torgersen, Torgersen, Torgersen, Torgersen, Torgerse~\n$ bill_length_mm    <dbl> 39.1, 39.5, 40.3, NA, 36.7, 39.3, 38.9, 39.2, 34.1, ~\n$ bill_depth_mm     <dbl> 18.7, 17.4, 18.0, NA, 19.3, 20.6, 17.8, 19.6, 18.1, ~\n$ flipper_length_mm <int> 181, 186, 195, NA, 193, 190, 181, 195, 193, 190, 186~\n$ body_mass_g       <int> 3750, 3800, 3250, NA, 3450, 3650, 3625, 4675, 3475, ~\n$ sex               <fct> male, female, female, NA, female, male, female, male~\n$ year              <int> 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007~\n```\n:::\n:::\n\n\n\n## Species\n\n@fig-bill-dims-species is a scatter plot of species of penguins.\n\n\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\nggplot(\n  penguins,\n  aes(\n    x = bill_length_mm, y = bill_depth_mm,\n    color = species, shape = species\n  )\n) +\n  geom_point() +\n  theme_minimal() +\n  scale_color_colorblind() +\n  labs(x = \"Bill length (mm)\", y = \"Bill depth (mm)\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 2 rows containing missing values (geom_point).\n```\n:::\n\n::: {.cell-output-display}\n![A scatterplot of penguins' bill depth and length, colored by\nspecies of penguins.\n](index_files/figure-pdf/fig-bill-dims-species-1.pdf){#fig-bill-dims-species fig-pos='H' fig-alt='A scatterplot of penguins\\' bill depth and length, colored by\nspecies of penguins. There is a relatively strong, linear\nassociation.\n'}\n:::\n:::\n\n\n\n## Penguins {.smaller}\n\n@tbl-penguins-top10 shows the first 10 penguins from the dataset.\n\n\n\n::: {#tbl-penguins-top10 .cell tbl-cap='First 10 penguins.'}\n\n```{.r .cell-code}\npenguins |>\n  slice_head(n = 10) |>\n  select(species, island, bill_length_mm, bill_depth_mm) |>\n  gt()\n```\n\n::: {.cell-output-display}\n\\captionsetup[table]{labelformat=empty,skip=1pt}\n\\begin{longtable}{ccrr}\n\\toprule\nspecies & island & bill\\_length\\_mm & bill\\_depth\\_mm \\\\ \n\\midrule\nAdelie & Torgersen & 39.1 & 18.7 \\\\ \nAdelie & Torgersen & 39.5 & 17.4 \\\\ \nAdelie & Torgersen & 40.3 & 18.0 \\\\ \nAdelie & Torgersen & NA & NA \\\\ \nAdelie & Torgersen & 36.7 & 19.3 \\\\ \nAdelie & Torgersen & 39.3 & 20.6 \\\\ \nAdelie & Torgersen & 38.9 & 17.8 \\\\ \nAdelie & Torgersen & 39.2 & 19.6 \\\\ \nAdelie & Torgersen & 34.1 & 18.1 \\\\ \nAdelie & Torgersen & 42.0 & 20.2 \\\\ \n\\bottomrule\n\\end{longtable}\n:::\n:::\n\n\n\n# Analysis\n\n## Modeling results\n\n## References\n",
    "supporting": [
      "index_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "\\usepackage{amsmath}\n\\usepackage{booktabs}\n\\usepackage{caption}\n\\usepackage{longtable}\n"
      ]
    },
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}