on:
  push:
    branches: main

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    container:
      image: rocker/verse:4.2.0
    steps:
      - name: Configure safe dir
        run: git config --system --add safe.directory '*'

      - name: Check out repository
        uses: actions/checkout@v3
        with:
           fetch-depth: 0
           set-safe-directory: '*'

      - name: Install packages used by R
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache: false
#          cache-version: 2
          packages: |
            any::ggthemes
            any::palmerpenguins
            any::gt

      - name: Use latest Quarto version
        run: |
          wget -q https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.104/quarto-1.4.104-linux-amd64.deb
          dpkg -i quarto-1.4.104-linux-amd64.deb
          rm quarto-1.4.104-linux-amd64.deb
          quarto install tinytex
          quarto check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions

      - name: Render and Publish
        run: |
          quarto render
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout gh-pages
          cp -r _site/* .
          git add .
          git commit -a -m "update pages" || echo "nothing to commit"
          git push https://${GITHUB_PAT}:${GITHUB_PAT}@github.com/${GITHUB_REPOSITORY}
          git checkout main
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

